version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db

    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  client:
    build: ./TwitterPocClient
    container_name: client
    ports:
      - 8080:80

  server:
    build:
      context: ./TwitterPoc
      dockerfile: ./TwitterPoc/Dockerfile
    container_name: server
    environment:
      - ASPNETCORE_URLS=http://+:80      
    ports:
      - 5000:80

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80